export declare const RUN_TEXT: readonly ["runs", 0, "text"];
export declare const TAB_CONTENT: readonly ["tabs", 0, "tabRenderer", "content"];
export declare const SINGLE_COLUMN_TAB: readonly ["contents", "singleColumnBrowseResultsRenderer", "tabs", 0, "tabRenderer", "content"];
export declare const SECTION_LIST: readonly ["sectionListRenderer", "contents"];
export declare const SECTION_LIST_ITEM: readonly ["sectionListRenderer", "contents", 0];
export declare const ITEM_SECTION: readonly ["itemSectionRenderer", "contents", 0];
export declare const MUSIC_SHELF: readonly ["musicShelfRenderer"];
export declare const GRID: readonly ["gridRenderer"];
export declare const GRID_ITEMS: readonly ["gridRenderer", "items"];
export declare const MENU: readonly ["menu", "menuRenderer"];
export declare const MENU_ITEMS: readonly ["menu", "menuRenderer", "items"];
export declare const MENU_LIKE_STATUS: readonly ["menu", "menuRenderer", "topLevelButtons", 0, "likeButtonRenderer", "likeStatus"];
export declare const MENU_SERVICE: readonly ["menuServiceItemRenderer", "serviceEndpoint"];
export declare const TOGGLE_MENU: "toggleMenuServiceItemRenderer";
export declare const PLAY_BUTTON: readonly ["overlay", "musicItemThumbnailOverlayRenderer", "content", "musicPlayButtonRenderer"];
export declare const NAVIGATION_BROWSE: readonly ["navigationEndpoint", "browseEndpoint"];
export declare const NAVIGATION_BROWSE_ID: readonly ["navigationEndpoint", "browseEndpoint", "browseId"];
export declare const PAGE_TYPE: readonly ["browseEndpointContextSupportedConfigs", "browseEndpointContextMusicConfig", "pageType"];
export declare const NAVIGATION_VIDEO_ID: readonly ["navigationEndpoint", "watchEndpoint", "videoId"];
export declare const NAVIGATION_PLAYLIST_ID: readonly ["navigationEndpoint", "watchEndpoint", "playlistId"];
export declare const NAVIGATION_WATCH_PLAYLIST_ID: readonly ["navigationEndpoint", "watchPlaylistEndpoint", "playlistId"];
export declare const NAVIGATION_VIDEO_TYPE: readonly ["watchEndpoint", "watchEndpointMusicSupportedConfigs", "watchEndpointMusicConfig", "musicVideoType"];
export declare const HEADER_DETAIL: readonly ["header", "musicDetailHeaderRenderer"];
export declare const DESCRIPTION_SHELF: readonly ["musicDescriptionShelfRenderer"];
export declare const DESCRIPTION: readonly ["description", "runs", 0, "text"];
export declare const CAROUSEL: readonly ["musicCarouselShelfRenderer"];
export declare const IMMERSIVE_CAROUSEL: readonly ["musicImmersiveCarouselShelfRenderer"];
export declare const CAROUSEL_CONTENTS: readonly ["musicCarouselShelfRenderer", "contents"];
export declare const CAROUSEL_TITLE: readonly ["header", "musicCarouselShelfBasicHeaderRenderer", "title", "runs", 0];
export declare const FRAMEWORK_MUTATIONS: string[];
export declare const TITLE: readonly ["title", "runs", 0];
export declare const TITLE_TEXT: readonly ["title", "runs", 0, "text"];
export declare const TEXT_RUNS: readonly ["text", "runs"];
export declare const TEXT_RUN: readonly ["text", "runs", 0];
export declare const TEXT_RUN_TEXT: readonly ["text", "runs", 0, "text"];
export declare const SUBTITLE: readonly ["subtitle", "runs", 0, "text"];
export declare const SUBTITLE2: readonly ["subtitle", "runs", 2, "text"];
export declare const SUBTITLE3: readonly ["subtitle", "runs", 4, "text"];
export declare const THUMBNAIL: readonly ["thumbnail", "thumbnails"];
export declare const THUMBNAILS: readonly ["thumbnail", "musicThumbnailRenderer", "thumbnail", "thumbnails"];
export declare const THUMBNAIL_RENDERER: readonly ["thumbnailRenderer", "musicThumbnailRenderer", "thumbnail", "thumbnails"];
export declare const THUMBNAIL_CROPPED: readonly ["thumbnail", "croppedSquareThumbnailRenderer", readonly ["thumbnail", "thumbnails"]];
export declare const FEEDBACK_TOKEN: readonly ["feedbackEndpoint", "feedbackToken"];
export declare const BADGE_LABEL: readonly ["badges", 0, "musicInlineBadgeRenderer", "accessibilityData", "accessibilityData", "label"];
export declare const RELOAD_CONTINUATION: readonly ["continuations", 0, "reloadContinuationData", "continuation"];
export declare const CATEGORY_TITLE: readonly ["musicNavigationButtonRenderer", "buttonText", "runs", 0, "text"];
export declare const CATEGORY_PARAMS: readonly ["musicNavigationButtonRenderer", "clickCommand", "browseEndpoint", "params"];
export declare const MRLIR: "musicResponsiveListItemRenderer";
export declare const MTRIR: "musicTwoRowItemRenderer";
export { nav } from '@codyduong/nav';
export declare function findObjectByKey<T extends Array<Record<string, any>>>(objectList: T | null, key: string, nested?: string, isKey?: boolean): any;
/** @deprecated Unused? */
